/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pasantia_proyect;

import errores.ErrorGeneral;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author A19B59953
 */
public class AgregarEditarVerFactura extends javax.swing.JFrame {
    
      
    public final static int AGREGAR = 1;
    public final static int EDITAR = 2;
    public final static int VER = 3;
    int opcion;
    private int facturaId;

    /**
     * Creates new form AgregarEditarVerFactura
     */
    public AgregarEditarVerFactura() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    public AgregarEditarVerFactura(int opcion, int categoriaId)throws SQLException{
    this.opcion = opcion;
    this.facturaId = facturaId;
    initComponents();
    
    ArrayList<ErrorGeneral> errores = new ArrayList<>();
    
    switch (opcion){
    case AGREGAR:
    createParaAgregar();
    break;
    case EDITAR:
    createParaEditar();
    break;
    case VER:
    createParaVer();
    break;
    default:
    break;
    
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_nombre1 = new javax.swing.JLabel();
        lbl_nombre2 = new javax.swing.JLabel();
        lbl_nombre3 = new javax.swing.JLabel();
        lbl_nombre4 = new javax.swing.JLabel();
        lbl_nombre5 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        combo_c = new javax.swing.JComboBox<>();
        combo_prov = new javax.swing.JComboBox<>();
        txt_monto = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnagregar = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("AGREGAR FACTURA");
        lbl_titulo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lbl_titulover(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jPanel2.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 32, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 500, 80));

        lbl_nombre1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_nombre1.setText("Comentario");
        jPanel1.add(lbl_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        lbl_nombre2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_nombre2.setText("Id proveedor");
        jPanel1.add(lbl_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lbl_nombre3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_nombre3.setText("Fecha");
        jPanel1.add(lbl_nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        lbl_nombre4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_nombre4.setText("Id categoria");
        jPanel1.add(lbl_nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        lbl_nombre5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_nombre5.setText("Monto");
        jPanel1.add(lbl_nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        fecha.setDateFormatString("yyyy-MMM-dd");
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 140, 30));

        combo_c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel1.add(combo_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 50, 30));

        combo_prov.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel1.add(combo_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 50, 30));

        txt_monto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_monto.setBorder(null);
        jPanel1.add(txt_monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 220, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 220, 20));

        btnagregar.setBackground(new java.awt.Color(51, 102, 0));
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconagregar.png"))); // NOI18N
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        btnregresar.setBackground(new java.awt.Color(51, 102, 0));
        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconregreso.png"))); // NOI18N
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 450, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_titulover(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbl_titulover

    }//GEN-LAST:event_lbl_titulover

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
      
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed

       

    }//GEN-LAST:event_btnregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
    ArrayList<ErrorGeneral> errores = new ArrayList<>();
    new AgregarEditarVerFactura(AgregarEditarVerCategoria.AGREGAR, 1).setVisible(true);
    new AgregarEditarVerFactura(AgregarEditarVerCategoria.EDITAR, 1).setVisible(true);
    new AgregarEditarVerFactura( AgregarEditarVerCategoria.VER, 1).setVisible(true);
    }catch (SQLException e) {
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JComboBox<String> combo_c;
    private javax.swing.JComboBox<String> combo_prov;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_nombre1;
    private javax.swing.JLabel lbl_nombre2;
    private javax.swing.JLabel lbl_nombre3;
    private javax.swing.JLabel lbl_nombre4;
    private javax.swing.JLabel lbl_nombre5;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextField txt_monto;
    // End of variables declaration//GEN-END:variables

    private void createParaAgregar() {
    lbl_titulo.setText("AGREGAR CATEGORIA");
    }

    private void createParaEditar() {
    lbl_titulo.setText("EDITAR CATEGORIA");
    btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeditar.png")));
    ArrayList<ErrorGeneral> errores = new ArrayList<>();
    }

    private void createParaVer() {
    lbl_titulo.setText("VER CATEGORIA");
    txt_monto.setEditable(false);
    txt_comentario.setEditable(false);
    combo_prov.setEnabled(false);
    combo_c.setEnabled(false);
    
    
    
        
                
        ArrayList<ErrorGeneral> errores = new ArrayList<>();
    }
}
