/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pasantia_proyect;

import Controladores.Categoria.ActualizarCategoria;
import Controladores.Categoria.AgregarCategoria;
import static Controladores.Categoria.AgregarCategoria.insertarCategoria;
import entidades.Categoria;
import errores.ErrorGeneral;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author A19B59953
 */
public class AgregarEditarVerCategoria extends javax.swing.JFrame {
    
    public final static int AGREGAR = 1;
    public final static int EDITAR = 2;
    public final static int VER = 3;
    int opcion;
    int categoriaId;

    
    /**
     * Creates new form categoria
     */
    public AgregarEditarVerCategoria() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    public AgregarEditarVerCategoria(int opcion, int categoriaId)throws SQLException{
    this.opcion = opcion;
    this.categoriaId = categoriaId;
    initComponents();
    
    ArrayList<ErrorGeneral> errores = new ArrayList<>();
    
    switch (opcion){
    case AGREGAR:
    createParaAgregar();
    break;
    case EDITAR:
    createParaEditar();
    break;
    case VER:
    createParaVer();
    break;
    default:
    break;
    
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_nombre1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnagregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("AGREGAR CATEGORIA");
        lbl_titulo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lbl_titulover(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(lbl_titulo)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(lbl_titulo)
                .addGap(34, 34, 34))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 90));

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_nombre.setText("Activo");
        jPanel1.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        lbl_nombre1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_nombre1.setText("Nombre");
        jPanel1.add(lbl_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nombre.setBorder(null);
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 220, 30));

        combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 220, 20));

        btnagregar.setBackground(new java.awt.Color(51, 102, 0));
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconagregar.png"))); // NOI18N
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 102, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconregreso.png"))); // NOI18N
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_titulover(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbl_titulover

    }//GEN-LAST:event_lbl_titulover

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
     if (opcion == AGREGAR) {
            agregarCategoria();
        } else if (opcion == EDITAR) {
            editarCategoria();
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    public static void main(String [] args) throws SQLException {

    try {
    new AgregarEditarVerCategoria(AgregarEditarVerCategoria.AGREGAR, 1).setVisible(true);
    new  AgregarEditarVerCategoria(AgregarEditarVerCategoria.EDITAR, 1).setVisible(true);
    new  AgregarEditarVerCategoria( AgregarEditarVerCategoria.VER, 1).setVisible(true);
    }catch (SQLException e) {
    }
}
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_nombre1;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

    private void createParaAgregar() {
      lbl_titulo.setText("AGREGAR CATEGORIA");
    }

    private void createParaEditar() {
    
        lbl_titulo.setText("EDITAR CATEGORIA");
        
    }

    private void createParaVer() {
       lbl_titulo.setText("VER CATEGORIA");
       txt_nombre.setEditable(false);
       combo.setEnabled(false);
    }

    private void agregarCategoria() {
    Categoria nuevaCategoria = obtenerDatosCategoria();

    int idCategoriaInsertada = AgregarCategoria.insertarCategoria(nuevaCategoria, new ArrayList<>());
    if (idCategoriaInsertada != -1) {
        JOptionPane.showMessageDialog(this, "Categoría agregada exitosamente con ID " + idCategoriaInsertada, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo agregar la categoría. Verifica los campos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private Categoria obtenerDatosCategoria() {
    
    return new Categoria(0, txt_nombre.getText(), false);
    }
    
    private void editarCategoria() {
    Categoria categoriaActualizada = obtenerDatosCategoria();

    int filasAfectadas = ActualizarCategoria.actualizarCategoria(categoriaActualizada, new ArrayList<>());
    if (filasAfectadas > 0) {
        JOptionPane.showMessageDialog(this, "Categoría actualizada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } else {
        {JOptionPane.showMessageDialog(this, "No se pudo actualizar la categoría. Verifica los campos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    }
}