/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pasantia_proyect;

import Controladores.DatabaseManager;
import Controladores.Pagos.ActualizarPago;
import Controladores.Pagos.Formas.ActualizarFormaPago;
import Controladores.Pagos.Formas.AgregarFormaPago;
import Controladores.Pagos.Formas.VerFormaPago;
import Controladores.Pagos.VerPago;
import entidades.FormaPago;
import entidades.Pagos;
import errores.ErrorGeneral;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author A19B59953
 */
public class AgregarEditarVerFormaPago extends javax.swing.JFrame {
    
    public final static int AGREGAR = 1;
    public final static int VER = 2;
    public final static int EDITAR = 3;
    int opcion;
    private int id_pago;
   

    /**
     * Creates new form forma_pago
     */
    public AgregarEditarVerFormaPago() {
        initComponents();
       
    }
    
    public AgregarEditarVerFormaPago(int opcion, int id_pago)throws SQLException{
    this.opcion = opcion;
    this.id_pago = id_pago;
    initComponents();
    setLocationRelativeTo(null);
    this.setResizable(false);
    ArrayList<ErrorGeneral> errores = new ArrayList<>();
    
    switch (opcion){
    case AGREGAR:
    createParaAgregar();
    break;
    case EDITAR:
    createParaEditar();
    break;
    case VER:
    createParaVer();
    break;
    default:
    break;
    
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_nombre1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        btn_regreso1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 450));
        setPreferredSize(new java.awt.Dimension(400, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(89, 111, 98));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("AGREGAR FORMA DE PAGO");
        lbl_titulo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lbl_titulover(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jPanel2.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 29, -1, -1));

        lbl_nombre1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_nombre1.setText("Nombre");

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnagregar.setBackground(new java.awt.Color(28, 49, 68));
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icons8-añadir-30.png"))); // NOI18N
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btn_regreso1.setBackground(new java.awt.Color(28, 49, 68));
        btn_regreso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/icons8-volver-30.png"))); // NOI18N
        btn_regreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regreso1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_regreso1)
                .addGap(18, 18, 18)
                .addComponent(btnagregar)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre1)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(lbl_nombre1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(btn_regreso1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnagregar)))
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_titulover(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbl_titulover

    }//GEN-LAST:event_lbl_titulover

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
     if (opcion == AGREGAR) {
            agregarPago();
        } else if (opcion == EDITAR) {
            editarPago();
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btn_regreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regreso1ActionPerformed
    this.setVisible(false);
    forma_pagofrm a = forma_pagofrm.obtenerInstanciaPrincipal();
    a.setVisible(true);
    a.actualizarTabla();      
    }//GEN-LAST:event_btn_regreso1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     try {
        ArrayList<ErrorGeneral> errores = new ArrayList<>();
        new AgregarEditarVerFormaPago(AgregarEditarVerFormaPago.VER, 1).setVisible(true);
       new AgregarEditarVerFormaPago(AgregarEditarVerFormaPago.EDITAR, 1).setVisible(true);
        new AgregarEditarVerFormaPago(AgregarEditarVerFormaPago.AGREGAR, 2).setVisible(true);
    } catch (SQLException e) {
    }   
    }
    
    private void createParaAgregar() {
    lbl_titulo.setText("AGREGAR FORMA DE PAGO");
    }
    
     private void createParaVer() {
    lbl_titulo.setText("VER FORMA DE PAGO");
    lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txt_nombre.setEditable(false);
    btnagregar.setEnabled(false);
      
    Font fuente = txt_nombre.getFont();
    float tamanoFuente = fuente.getSize() + 2; 
    txt_nombre.setFont(fuente.deriveFont(tamanoFuente));
    
    ArrayList<ErrorGeneral> errores = new ArrayList<>();
    rellenarVentana(id_pago, errores);
    }
     
    private void rellenarVentana(int id_pago, ArrayList<ErrorGeneral> errores) {
    
    FormaPago FPEncontrada = VerFormaPago.verFP(id_pago, errores);

    if (FPEncontrada != null) {
        txt_nombre.setText(FPEncontrada.getNombreFormaPago());
    } else {
        System.out.println("No se pudo encontrar la forma de pago con ID: " + id_pago);
    }
}

    
   private void agregarPago() {
    String nombreFormaPago = txt_nombre.getText();

        FormaPago nuevaFormaPago = new FormaPago(0, nombreFormaPago);

        ArrayList<ErrorGeneral> errores = new ArrayList<>();
        int idInsertado = AgregarFormaPago.insertarFP(nuevaFormaPago, errores);

        if (idInsertado != -1) {
            JOptionPane.showMessageDialog(this, "Forma de pago agregada correctamente con ID " + idInsertado, "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            mostrarErrores(errores);
        }
}
   
 private void editarPago() {
    String nombreFormaPago = txt_nombre.getText();

    int idFormaPago = id_pago;

    FormaPago formaPagoActualizar = new FormaPago(idFormaPago, nombreFormaPago);
    ArrayList<ErrorGeneral> errores = new ArrayList<>();
    int filasAfectadas = ActualizarFormaPago.actualizarFP(formaPagoActualizar, errores);
    if (filasAfectadas > 0) {
        JOptionPane.showMessageDialog(this, "Forma de pago actualizada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
      
    } else {
        
        mostrarErrores(errores);
    }
}


   
   private static void mostrarErrores(ArrayList<ErrorGeneral> errores) {
        if (!errores.isEmpty()) {
            StringBuilder mensaje = new StringBuilder("Se han producido los siguientes errores:\n\n");

            for (ErrorGeneral error : errores) {
                mensaje.append("Error: ").append(error.getMensajeError()).append("\n");
                mensaje.append("Solución: ").append(error.getMensajeSolucion()).append("\n\n");
            }

            JOptionPane.showMessageDialog(null, mensaje.toString(), "Errores", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regreso1;
    private javax.swing.JButton btnagregar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_nombre1;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

    private void createParaEditar() {
       lbl_titulo.setText("EDITAR FORMA DE PAGO");
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img//icons//icons8-editar-30.png")));
        ArrayList<ErrorGeneral> errores = new ArrayList<>();
        rellenarVentana(id_pago, errores);
    }
}
