/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pasantia_proyect;

import Controladores.MyConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A19B59953
 */
public class areafrm extends javax.swing.JFrame {
    
    private static areafrm instanciaPrincipal;

    /**
     * Creates new form areafrm
     */
    public areafrm() {
        initComponents();
        mostrar("area");
        instanciaPrincipal = this;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    
    
     public static areafrm obtenerInstanciaPrincipal() {
        return instanciaPrincipal;
    }
     
     public void actualizarTabla() {
     mostrar("area");
}
    
    private DefaultTableModel tableModel;
    
    public void mostrar (String tabla){
    
    if (tableModel == null) {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("ID");
        tableModel.addColumn("Nombre");
        jTable.setModel(tableModel);
        jTable.getColumnModel().getColumn(0).setMinWidth(0);
        jTable.getColumnModel().getColumn(0).setMaxWidth(0);
    } else {
       
        tableModel.setRowCount(0);
    }
    
    String sql = "select * from " + tabla;
    Statement st;
    MyConnection cc = new MyConnection();
    Connection cn = MyConnection.getConnection();
    
    String[] datos = new String[2];

    try {
        st = cn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            datos[0] = rs.getString(1);
            datos[1] = rs.getString(2);
            tableModel.addRow(datos);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error" + e.toString());
    }
    
    }
    
     public int obtenerIdAreaSeleccionada() {
    int filaSeleccionada = jTable.getSelectedRow();
    if (filaSeleccionada != -1) {
        return Integer.parseInt(jTable.getValueAt(filaSeleccionada, 0).toString()); 
    } else {
        return -1; 
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btn_act = new javax.swing.JButton();
        ver_btn = new javax.swing.JButton();
        btn_añadir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("AREA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/c.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 450, 440));

        btn_act.setBackground(new java.awt.Color(51, 102, 0));
        btn_act.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-actualizar-40 (1).png"))); // NOI18N
        btn_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actActionPerformed(evt);
            }
        });
        jPanel1.add(btn_act, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        ver_btn.setBackground(new java.awt.Color(51, 102, 0));
        ver_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ver-40.png"))); // NOI18N
        ver_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_btnActionPerformed(evt);
            }
        });
        jPanel1.add(ver_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        btn_añadir.setBackground(new java.awt.Color(51, 102, 0));
        btn_añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconagregar.png"))); // NOI18N
        btn_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));

        btn_editar.setBackground(new java.awt.Color(51, 102, 0));
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeditar.png"))); // NOI18N
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actActionPerformed
    actualizarTabla();    
    }//GEN-LAST:event_btn_actActionPerformed

    private void ver_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_btnActionPerformed
     int idAreaSeleccionada = obtenerIdAreaSeleccionada();
    if (idAreaSeleccionada != -1) {
        try {
            new AgregarEditarVerArea(AgregarEditarVerArea.VER, idAreaSeleccionada).setVisible(true);
        } catch (SQLException e) {
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una area antes de ver sus datos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_ver_btnActionPerformed

    private void btn_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirActionPerformed
       try {
        new AgregarEditarVerArea(AgregarEditarVerArea.AGREGAR, -1).setVisible(true);
    } catch (SQLException e) {
    }
    }//GEN-LAST:event_btn_añadirActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
     int idAreaSeleccionada = obtenerIdAreaSeleccionada();
    if (idAreaSeleccionada != -1) {
        try {
          
            new AgregarEditarVerArea(AgregarEditarVerArea.EDITAR, idAreaSeleccionada).setVisible(true);
        } catch (SQLException e) {
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una area antes de editar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btn_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(areafrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(areafrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(areafrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(areafrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new areafrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_act;
    private javax.swing.JButton btn_añadir;
    private javax.swing.JButton btn_editar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JButton ver_btn;
    // End of variables declaration//GEN-END:variables
}
