package pasantia_proyect;


import Controladores.Actualizar;
import static Controladores.Actualizar.actProveedor;
import Controladores.MyConnection;
import Controladores.Proveedor.ProveedoresIndex;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Component;
import Controladores.Ver;
import entidades.Proveedor;
import errores.ErrorGeneral;
import java.sql.Connection;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import pasantia_proyect.AgregarEditarVerProveedor;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author A19B59953
 */
public class consulta extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    DefaultTableModel prov;
    
    public consulta() {
        initComponents();
        this.setLocationRelativeTo(null);
        prov = new DefaultTableModel();
        table_prov.setModel(prov);
        Mostrardatos("");
    }

     public void RefrescarTabla() {

        try {

            prov.setColumnCount(0);
            prov.setRowCount(0);
           

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
    }
     
    private void buscarDatos() {
    proveedoresIndex = new ProveedoresIndex(); 
    MyConnection cc = new MyConnection();
    Connection cn = MyConnection.getConnection();

    RefrescarTabla();

    Integer codigoProveedor = Integer.parseInt(txtCodigo.getText());
    String nombreProveedor = txtNombre.getText();
   

    ArrayList<ErrorGeneral> errores = new ArrayList<>();
    
    try {
        List<Proveedor> proveedores = proveedoresIndex.verProveedorDos(codigoProveedor, nombreProveedor, null, false, null, errores);

       
        for (Proveedor proveedor : proveedores) {
           
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al realizar la búsqueda", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    

    public final void Mostrardatos(String valor) {
  
        MyConnection cc = new MyConnection();

        Connection cn = MyConnection.getConnection();


        RefrescarTabla();

        prov.addColumn("Id");
        prov.addColumn("Nombre");
        prov.addColumn("Teléfono");
        prov.addColumn("Activo");
        prov.addColumn("Límite de crédito");
      

        this.table_prov.setModel(prov);
        
         String sql = null;

    if (valor.equals("")) {
      
        String busqueda = buscar_txt.getText();

        
        sql = "SELECT * FROM proveedor WHERE nombre LIKE '%" + busqueda + "%'";
    }

        String[] datos = new String[5];

        try {

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getBoolean(4) ? "Sí" : "No";
                datos[4] = rs.getString(5);

                prov.addRow(datos);
            }
            
          TableColumnModel tcm = table_prov.getColumnModel();
          int idColumnIndex = 0; 


          tcm.getColumn(idColumnIndex).setMinWidth(0);
          tcm.getColumn(idColumnIndex).setMaxWidth(0);
          tcm.getColumn(idColumnIndex).setWidth(0);


            table_prov.setModel(prov);
        } catch (SQLException ex) {


            JOptionPane.showMessageDialog(null, "Error" + ex);
        }

    }
    
    /**
     *
     */
   

    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_prov = new javax.swing.JTable();
        btn_añadir = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        buscar_txt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CERCANCI");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Centro Cardiorenal del Cibao");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        table_prov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_prov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_prov);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 470, 320));

        btn_añadir.setBackground(new java.awt.Color(51, 102, 0));
        btn_añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconagregar.png"))); // NOI18N
        btn_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        btn_ver.setBackground(new java.awt.Color(51, 102, 0));
        btn_ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ver-40.png"))); // NOI18N
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        btn_editar.setBackground(new java.awt.Color(51, 102, 0));
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeditar.png"))); // NOI18N
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        btn_buscar.setBackground(new java.awt.Color(51, 102, 0));
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sincronizar-30.png"))); // NOI18N
        btn_buscar.setBorder(null);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 40, 40));

        buscar_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscar_txt.setBorder(null);
        jPanel1.add(buscar_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 150, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirActionPerformed
    AgregarEditarVerProveedor w = new AgregarEditarVerProveedor();
    w.setVisible(true);
    w.pack();
    this.dispose();
    }//GEN-LAST:event_btn_añadirActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
     int filaSeleccionada = table_prov.getSelectedRow();

    if (filaSeleccionada != -1) {
        String idStr = table_prov.getValueAt(filaSeleccionada, 0).toString();

        try {
            int proveedorId = Integer.parseInt(idStr);

            ArrayList<ErrorGeneral> errores = null;
            Proveedor editar = Ver.verProveedor(proveedorId, errores);

            AgregarEditarVerProveedor w = new AgregarEditarVerProveedor(AgregarEditarVerProveedor.EDITAR, proveedorId, errores);
            w.setVisible(true);
            w.pack();
            this.dispose();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El valor en la columna de ID no es un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un proveedor antes de presionar el botón de editar", "Aviso", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed

    int filaSeleccionada = table_prov.getSelectedRow();

    if (filaSeleccionada != -1) {
        int proveedorId = Integer.parseInt(table_prov.getValueAt(filaSeleccionada, 0).toString());

        try {
            ArrayList<ErrorGeneral> errores = null;
            Proveedor ver = Ver.verProveedor(proveedorId, errores);

            AgregarEditarVerProveedor w = new AgregarEditarVerProveedor(AgregarEditarVerProveedor.VER, proveedorId, errores);
            w.setVisible(true);
            w.pack();
            this.dispose();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un proveedor antes de presionar el botón de ver", "Aviso", JOptionPane.WARNING_MESSAGE);
    }
    
    }//GEN-LAST:event_btn_verActionPerformed

    private void clicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicked
       
    }//GEN-LAST:event_clicked

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
  Mostrardatos("");
        
    }//GEN-LAST:event_btn_buscarActionPerformed
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadir;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_ver;
    private javax.swing.JTextField buscar_txt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table_prov;
    // End of variables declaration//GEN-END:variables

    
}
